---
- name: 5.1 - Ensure legacy services and clients are not present
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - nis
    - rsh-server
    - rsh-client
    - rsh-redone-client
    - talkd
    - talk
    - telnet-server
    - tftp
    - atftp
    - xinetd
  become: "true"

- name: 5.1.8 - Ensure xinetd is not enabled
  shell: update-rc.d xinetd disable
  become: "true"
