---
# tasks file for debian-hardening

# Section 1 - Software Updates
- include: 1-updates.yml
  tags: updates

# Section 3- Secure Boot Settings
- include: 3-secure-boot.yml
  tags: secure-boot

# Section 3- Secure Boot Settings
- include: 4-process-hardening.yml
  tags: process-hardening
  
# Section 3- Secure Boot Settings
- include: 5-os-services.yml
  tags: os-services